name=input('Enter the Name ')
Branch=input('Enter the Branch')
Gender=input('Enter the Gender')
College=input('Enter the College')
Age=(int)(input('Enter the age'))
print('Name',name)
print('Branch',Branch)
print('Gender',Gender)
print('College',College)
print('Age',Age)
